language: cpp
compiler: gcc
dist: bionic
os: linux

addons:
  apt:
    packages:
     - cmake-data
     - cmake

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - test -n $CC && unset CC
  - pip install --user cpp-coveralls

install: 
  - sudo apt-get install -qq g++-9
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
  - sudo apt-get install libopenmpi-dev openmpi-bin
# TODO: add MPICH and proper OpenMPI Version


before_script:
  - echo "Versions:\n" & g++ --version && cmake --version && mpirun --version
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS=ON -DENABLE_COVERALLS_REPORT=ON -DGENERATE_DOCUMENTATION=OFF .. 

script: 
  - make -j $(nproc)
  - ctest --output-on-failure


after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"
