language: cpp
compiler: gcc
dist: bionic


addons:
  apt:
    packages: 
     - lcov
     - cmake-data
     - cmake
     - libopenmpi-dev
     - openmpi-bin
     - g++-9 

before_script:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DENABLE_COVERAGE=ON ..


script: 
  - make


after_success:
# Create lcov report
# capture coverage info
- lcov --directory . --capture --output-file coverage.info
# filter out system and extra files.
# To also not include test code in coverage add them with full path to the patterns: '*/tests/*'
- lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
# output coverage data for debugging (optional)
- lcov --list coverage.info
# Uploading to CodeCov
# '-f' specifies file(s) to use and disables manual coverage gathering and file search which has already been done above
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
