name: Generate documentation

on: [push]

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      # checkout repository
      - uses: actions/checkout@v2
      # mimic CMake's configure step for current setup
      - name: Configure
        run: |
          sed -i -e 's/@CMAKE_SOURCE_DIR@\///g' doc/Doxyfile.in
          sed -i -e 's/@PROJECT_SOURCE_DIR@\///g' doc/Doxyfile.in
          sed -i -e 's/@CMAKE_CURRENT_SOURCE_DIR@//g' doc/Doxyfile.in
          grep 'VERSION "' CMakeLists.txt | sed -n '/"/!{/\n/{P;b}};s/"/\n/g;D' | xargs -I {} sed -i -e 's/@mpicxx_VERSION@/{}/g' doc/Doxyfile.in
      # generate documentation using doxygen
      - name: Generate
        uses: arkantos493/doxygen-action@v2.1.0
        with:
          doxyfile-path: "doc/Doxyfile.in"
          working-directory: "."
      # minify files
      - name: Minify
        run: |
          sudo apt-get install nodejs npm
          mkdir -p minify/node_modules
          npm install --prefix ./minify uglify-js -g
          npm install --prefix ./minify clean-css-cli -g
          npm install --prefix ./minify html-minifier -g
          for i in `find doc/html/ -type f -name "*.js"`; do ./minify/lib/node_modules/uglify-js/bin/uglifyjs --compress --mangle --toplevel $i -o $i; done
          for i in `find doc/html/ -type f -name "*.css"`; do ./minify/lib/node_modules/clean-css-cli/bin/cleancss $i -o $i; done
          for i in `find doc/html/ -type f -name "*.html"`; do ./minify/lib/node_modules/html-minifier/bin/cli.js --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true $i -o $i; done
      # deploy generated documentation using github.io
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/html