name: Generate documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout repository
      - uses: actions/checkout@v2
      # mimic CMake's configure step for current setup
      - name: Configure
        run: |
          sed -i -e 's/@CMAKE_SOURCE_DIR@\///g' doc/Doxyfile.in
          sed -i -e 's/@PROJECT_SOURCE_DIR@\///g' doc/Doxyfile.in
          sed -i -e 's/@CMAKE_CURRENT_SOURCE_DIR@//g' doc/Doxyfile.in
          grep 'VERSION "' CMakeLists.txt | sed -n '/"/!{/\n/{P;b}};s/"/\n/g;D' | xargs -I {} sed -i -e 's/@mpicxx_VERSION@/{}/g' doc/Doxyfile.in
      # generate documentation using doxygen
      - name: Generate
        uses: arkantos493/doxygen-action@v2.1.0
        with:
          doxyfile-path: "doc/Doxyfile.in"
          working-directory: "."
      # deploy generated documentation using github.io
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/html