name: Generate documentation

# only trigger this action on specific events
on:
  push:
    branches:
      - master
      - init_and_finalize
  pull_request:
    branches:
      - master

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      # checkout repository
      - name: Checkout mpicxx
        uses: actions/checkout@v2
        with:
          repository: arkantos493/MPICXX
          path: mpicxx
      # fix errors before configuration
      - name: Before Generation
        run: |
          cd mpicxx
          ls
          sed '/^!\[/d;/^\[!\[/d' README.md | cat -s > doc/resources/main_page.md
      # mimic CMake's configure step for current setup
      - name: Configure
        run: |
          sed -i -e 's/@PROJECT_SOURCE_DIR@\///g' doc/Doxyfile.in
          grep 'VERSION "' CMakeLists.txt | sed -n '/"/!{/\n/{P;b}};s/"/\n/g;D' | xargs -I {} sed -i -e 's/@mpicxx_VERSION@/{}/g' doc/Doxyfile.in
      # generate documentation using doxygen
      - name: Generate
        uses: arkantos493/doxygen-action@v2.1.0
        with:
          doxyfile-path: "doc/Doxyfile.in"
          working-directory: "."
      # fix errors after generation
      - name: After Generation
        run: |
          cp doc/html/customdoxygen.css doc/html/search/customdoxygen.css
          cat doc/resources/customsearch.js >> doc/html/search/search.js
      # deploy generated documentation using github.io
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/html